name: build & tests & release

on:
  push:
    tags:
      - "v*.*.*"

env:
  DOTNET_VERSION: "9.0.x"
  PROFILE: Release # Release | Debug
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages # Since env cannot be specified in composite action, specify cache dir individually.

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Ref: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net#building-and-testing-your-code
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Set output paths
        id: set_paths
        shell: pwsh
        run: |
          $output_dir='./Pandora Behaviour Engine/bin/${{ env.PROFILE }}/net9.0'
          $zip_file_name='Pandora_Behaviour_Engine_${{ github.ref_name }}.zip'
          $zip_dir='./Output'

          echo "output_dir=$output_dir" >> $env:GITHUB_OUTPUT

          # NOTE: If we don't create a dir, we'll get an error when using `Compress-Archive`.
          New-Item -ItemType Directory -Force -Path $zip_dir | Out-Null
          $zip_path="$zip_dir/$zip_file_name"
          echo "zip_path=$zip_path" >> $env:GITHUB_OUTPUT

      - name: Build & Test -> Upload a Build Artifact
        uses: ./.github/actions/build-and-test
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          configuration: ${{ env.PROFILE }}
          solution-path: "./Pandora+.sln"
          output-dir: ${{ steps.set_paths.outputs.output_dir }}

      - name: Zip and Release
        uses: ./.github/actions/zip-and-release
        with:
          title: Pandora Behaviour Engine ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          output-dir: ${{ steps.set_paths.outputs.output_dir }}
          zip-path: ${{ steps.set_paths.outputs.zip_path }}
