name: build & tests

on: [push, pull_request]

env:
  DOTNET_VERSION: "9.0.x"
  PROFILE: Debug # Release | Debug
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages # Since env cannot be specified in composite action, specify cache dir individually.

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 1

      # `GITHUB_OUTPUT` ref: https://docs.github.com/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter
      - name: Set output paths
        id: set_paths
        run: echo "output_dir=./Pandora Behaviour Engine/bin/${{ env.PROFILE }}/net9.0" >> $GITHUB_OUTPUT

      - name: Build & Test
        uses: ./.github/actions/build-and-test
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          configuration: ${{ env.PROFILE }}
          solution-path: "./Pandora+.sln"
          output-dir: ${{ steps.set_paths.outputs.output_dir }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Pandora.Behaviour.Engine
          path: ${{ steps.set_paths.outputs.output_dir }}
